### ISSUE TITLE
Dock/Undockに失敗する

### ISSUE THREAD

**Issue by sktometometo** [sktometometo/jsk_robot#144]
たまにDockに失敗する。

**Comment by mqcmd196** [comment]
自分たちがいないときに発生するからデバッグが難しすぎる...

Undockしたときにすぐ座り込んでコケるというパターンと，Dockに本当に失敗しているパターンがある気がしていて，独立な問題なのか，それともお互い関係ある問題なのか少し気になります．

**Comment by sktometometo** [comment]
https://github.com/sktometometo/spot_ros/pull/13/files

Undock すると spot_wrapper の is_standing が Trueにならないので, AsynIdle で 毎回 standさせないために undock した際に 座るのかと思って変更した. ついでに dock/undock字のrobotクライアントを spot_wrapper で持っているものと共通にした。

**Comment by sktometometo** [comment]
ただ、今でもundock字に勝手に座ることはあるのでまだ完全には治っていなさそう。

**Comment by sktometometo** [comment]
https://github.com/sktometometo/spot_ros/pull/15 で直ったかも?様子見する。
